# Generated by Django 5.2.13 on 2026-04-14 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_public', models.BooleanField(default=False)),
                ('cover_backdrop', models.CharField(blank=True, default='', help_text='TMDB backdrop path used as the collection cover image', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('genre', 'Genre'), ('year_min', 'Year (min)'), ('year_max', 'Year (max)'), ('rating_min', 'Rating (min)'), ('rating_max', 'Rating (max)'), ('runtime_min', 'Runtime min (minutes)'), ('runtime_max', 'Runtime max (minutes)'), ('language', 'Original language'), ('sort_by', 'Sort order')], max_length=20)),
                ('value', models.CharField(max_length=200)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='recommendations.collection')),
            ],
            options={
                'ordering': ['field'],
            },
        ),
    ]
